# Generated by Django 4.0.3 on 2023-12-18 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 22, 44, 51, 875950, tzinfo=utc)),
        ),
    ]
