# Generated by Django 4.0.3 on 2023-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='special_vip',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
