# Generated by Django 4.0.3 on 2023-12-18 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_appointment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 22, 45, 56, 235932, tzinfo=utc)),
        ),
    ]
