# Generated by Django 4.0.3 on 2023-12-19 00:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_appointment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 0, 56, 42, 596279, tzinfo=utc)),
        ),
    ]
