# Generated by Django 4.0.3 on 2023-12-19 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_date_time_alter_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 2, 29, 29, 841415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
